// Code generated by protoc-gen-go. DO NOT EDIT.
// source: callscoring.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetScoringConfigurationsRequest struct {
	SortField            string   `protobuf:"bytes,1,opt,name=sort_field,json=sortField,proto3" json:"sort_field,omitempty"`
	SortDirection        string   `protobuf:"bytes,2,opt,name=sort_direction,json=sortDirection,proto3" json:"sort_direction,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	IsEnabled            *Flag    `protobuf:"bytes,4,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	IsProd               *Flag    `protobuf:"bytes,5,opt,name=is_prod,json=isProd,proto3" json:"is_prod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetScoringConfigurationsRequest) Reset()         { *m = GetScoringConfigurationsRequest{} }
func (m *GetScoringConfigurationsRequest) String() string { return proto.CompactTextString(m) }
func (*GetScoringConfigurationsRequest) ProtoMessage()    {}
func (*GetScoringConfigurationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{0}
}

func (m *GetScoringConfigurationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetScoringConfigurationsRequest.Unmarshal(m, b)
}
func (m *GetScoringConfigurationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetScoringConfigurationsRequest.Marshal(b, m, deterministic)
}
func (m *GetScoringConfigurationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetScoringConfigurationsRequest.Merge(m, src)
}
func (m *GetScoringConfigurationsRequest) XXX_Size() int {
	return xxx_messageInfo_GetScoringConfigurationsRequest.Size(m)
}
func (m *GetScoringConfigurationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetScoringConfigurationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetScoringConfigurationsRequest proto.InternalMessageInfo

func (m *GetScoringConfigurationsRequest) GetSortField() string {
	if m != nil {
		return m.SortField
	}
	return ""
}

func (m *GetScoringConfigurationsRequest) GetSortDirection() string {
	if m != nil {
		return m.SortDirection
	}
	return ""
}

func (m *GetScoringConfigurationsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetScoringConfigurationsRequest) GetIsEnabled() *Flag {
	if m != nil {
		return m.IsEnabled
	}
	return nil
}

func (m *GetScoringConfigurationsRequest) GetIsProd() *Flag {
	if m != nil {
		return m.IsProd
	}
	return nil
}

type Flag struct {
	Do                   bool     `protobuf:"varint,1,opt,name=do,proto3" json:"do,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Flag) Reset()         { *m = Flag{} }
func (m *Flag) String() string { return proto.CompactTextString(m) }
func (*Flag) ProtoMessage()    {}
func (*Flag) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{1}
}

func (m *Flag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Flag.Unmarshal(m, b)
}
func (m *Flag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Flag.Marshal(b, m, deterministic)
}
func (m *Flag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flag.Merge(m, src)
}
func (m *Flag) XXX_Size() int {
	return xxx_messageInfo_Flag.Size(m)
}
func (m *Flag) XXX_DiscardUnknown() {
	xxx_messageInfo_Flag.DiscardUnknown(m)
}

var xxx_messageInfo_Flag proto.InternalMessageInfo

func (m *Flag) GetDo() bool {
	if m != nil {
		return m.Do
	}
	return false
}

type GetRuleByIdRequest struct {
	RuleId               int64    `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRuleByIdRequest) Reset()         { *m = GetRuleByIdRequest{} }
func (m *GetRuleByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetRuleByIdRequest) ProtoMessage()    {}
func (*GetRuleByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{2}
}

func (m *GetRuleByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRuleByIdRequest.Unmarshal(m, b)
}
func (m *GetRuleByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRuleByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetRuleByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRuleByIdRequest.Merge(m, src)
}
func (m *GetRuleByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetRuleByIdRequest.Size(m)
}
func (m *GetRuleByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRuleByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRuleByIdRequest proto.InternalMessageInfo

func (m *GetRuleByIdRequest) GetRuleId() int64 {
	if m != nil {
		return m.RuleId
	}
	return 0
}

type GetConfigByIdRequest struct {
	ConfigId             int64    `protobuf:"varint,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigByIdRequest) Reset()         { *m = GetConfigByIdRequest{} }
func (m *GetConfigByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigByIdRequest) ProtoMessage()    {}
func (*GetConfigByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{3}
}

func (m *GetConfigByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigByIdRequest.Unmarshal(m, b)
}
func (m *GetConfigByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigByIdRequest.Merge(m, src)
}
func (m *GetConfigByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigByIdRequest.Size(m)
}
func (m *GetConfigByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigByIdRequest proto.InternalMessageInfo

func (m *GetConfigByIdRequest) GetConfigId() int64 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

type ScoreCallRequest struct {
	CallId               int64          `protobuf:"varint,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	CallDirection        string         `protobuf:"bytes,2,opt,name=call_direction,json=callDirection,proto3" json:"call_direction,omitempty"`
	HasInquiry           bool           `protobuf:"varint,3,opt,name=has_inquiry,json=hasInquiry,proto3" json:"has_inquiry,omitempty"`
	Inquiry              *Inquiry       `protobuf:"bytes,4,opt,name=inquiry,proto3" json:"inquiry,omitempty"`
	HasContact           bool           `protobuf:"varint,5,opt,name=has_contact,json=hasContact,proto3" json:"has_contact,omitempty"`
	Contact              *Contact       `protobuf:"bytes,6,opt,name=contact,proto3" json:"contact,omitempty"`
	IsScheduled          bool           `protobuf:"varint,7,opt,name=is_scheduled,json=isScheduled,proto3" json:"is_scheduled,omitempty"`
	ScheduledTask        *ScheduledTask `protobuf:"bytes,8,opt,name=scheduled_task,json=scheduledTask,proto3" json:"scheduled_task,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ScoreCallRequest) Reset()         { *m = ScoreCallRequest{} }
func (m *ScoreCallRequest) String() string { return proto.CompactTextString(m) }
func (*ScoreCallRequest) ProtoMessage()    {}
func (*ScoreCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{4}
}

func (m *ScoreCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScoreCallRequest.Unmarshal(m, b)
}
func (m *ScoreCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScoreCallRequest.Marshal(b, m, deterministic)
}
func (m *ScoreCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScoreCallRequest.Merge(m, src)
}
func (m *ScoreCallRequest) XXX_Size() int {
	return xxx_messageInfo_ScoreCallRequest.Size(m)
}
func (m *ScoreCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScoreCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScoreCallRequest proto.InternalMessageInfo

func (m *ScoreCallRequest) GetCallId() int64 {
	if m != nil {
		return m.CallId
	}
	return 0
}

func (m *ScoreCallRequest) GetCallDirection() string {
	if m != nil {
		return m.CallDirection
	}
	return ""
}

func (m *ScoreCallRequest) GetHasInquiry() bool {
	if m != nil {
		return m.HasInquiry
	}
	return false
}

func (m *ScoreCallRequest) GetInquiry() *Inquiry {
	if m != nil {
		return m.Inquiry
	}
	return nil
}

func (m *ScoreCallRequest) GetHasContact() bool {
	if m != nil {
		return m.HasContact
	}
	return false
}

func (m *ScoreCallRequest) GetContact() *Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

func (m *ScoreCallRequest) GetIsScheduled() bool {
	if m != nil {
		return m.IsScheduled
	}
	return false
}

func (m *ScoreCallRequest) GetScheduledTask() *ScheduledTask {
	if m != nil {
		return m.ScheduledTask
	}
	return nil
}

type Inquiry struct {
	CreatedDt            int64    `protobuf:"varint,1,opt,name=created_dt,json=createdDt,proto3" json:"created_dt,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Partner              string   `protobuf:"bytes,3,opt,name=partner,proto3" json:"partner,omitempty"`
	Source               string   `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	CreationMethod       string   `protobuf:"bytes,5,opt,name=creation_method,json=creationMethod,proto3" json:"creation_method,omitempty"`
	ProviderChain        string   `protobuf:"bytes,6,opt,name=provider_chain,json=providerChain,proto3" json:"provider_chain,omitempty"`
	CareType             string   `protobuf:"bytes,7,opt,name=care_type,json=careType,proto3" json:"care_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Inquiry) Reset()         { *m = Inquiry{} }
func (m *Inquiry) String() string { return proto.CompactTextString(m) }
func (*Inquiry) ProtoMessage()    {}
func (*Inquiry) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{5}
}

func (m *Inquiry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inquiry.Unmarshal(m, b)
}
func (m *Inquiry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inquiry.Marshal(b, m, deterministic)
}
func (m *Inquiry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inquiry.Merge(m, src)
}
func (m *Inquiry) XXX_Size() int {
	return xxx_messageInfo_Inquiry.Size(m)
}
func (m *Inquiry) XXX_DiscardUnknown() {
	xxx_messageInfo_Inquiry.DiscardUnknown(m)
}

var xxx_messageInfo_Inquiry proto.InternalMessageInfo

func (m *Inquiry) GetCreatedDt() int64 {
	if m != nil {
		return m.CreatedDt
	}
	return 0
}

func (m *Inquiry) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Inquiry) GetPartner() string {
	if m != nil {
		return m.Partner
	}
	return ""
}

func (m *Inquiry) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Inquiry) GetCreationMethod() string {
	if m != nil {
		return m.CreationMethod
	}
	return ""
}

func (m *Inquiry) GetProviderChain() string {
	if m != nil {
		return m.ProviderChain
	}
	return ""
}

func (m *Inquiry) GetCareType() string {
	if m != nil {
		return m.CareType
	}
	return ""
}

type Contact struct {
	EmailValid           bool     `protobuf:"varint,1,opt,name=email_valid,json=emailValid,proto3" json:"email_valid,omitempty"`
	PhoneValid           bool     `protobuf:"varint,2,opt,name=phone_valid,json=phoneValid,proto3" json:"phone_valid,omitempty"`
	Relationship         string   `protobuf:"bytes,3,opt,name=relationship,proto3" json:"relationship,omitempty"`
	NumPriorCall         int64    `protobuf:"varint,4,opt,name=num_prior_call,json=numPriorCall,proto3" json:"num_prior_call,omitempty"`
	NumCallIn_30         int64    `protobuf:"varint,5,opt,name=num_call_in_30,json=numCallIn30,proto3" json:"num_call_in_30,omitempty"`
	NumCallIn_90         int64    `protobuf:"varint,6,opt,name=num_call_in_90,json=numCallIn90,proto3" json:"num_call_in_90,omitempty"`
	NumCallIn_180        int64    `protobuf:"varint,7,opt,name=num_call_in_180,json=numCallIn180,proto3" json:"num_call_in_180,omitempty"`
	PriorQual            bool     `protobuf:"varint,8,opt,name=prior_qual,json=priorQual,proto3" json:"prior_qual,omitempty"`
	CreatedDt            int64    `protobuf:"varint,9,opt,name=created_dt,json=createdDt,proto3" json:"created_dt,omitempty"`
	LastContactDt        int64    `protobuf:"varint,10,opt,name=last_contact_dt,json=lastContactDt,proto3" json:"last_contact_dt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{6}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetEmailValid() bool {
	if m != nil {
		return m.EmailValid
	}
	return false
}

func (m *Contact) GetPhoneValid() bool {
	if m != nil {
		return m.PhoneValid
	}
	return false
}

func (m *Contact) GetRelationship() string {
	if m != nil {
		return m.Relationship
	}
	return ""
}

func (m *Contact) GetNumPriorCall() int64 {
	if m != nil {
		return m.NumPriorCall
	}
	return 0
}

func (m *Contact) GetNumCallIn_30() int64 {
	if m != nil {
		return m.NumCallIn_30
	}
	return 0
}

func (m *Contact) GetNumCallIn_90() int64 {
	if m != nil {
		return m.NumCallIn_90
	}
	return 0
}

func (m *Contact) GetNumCallIn_180() int64 {
	if m != nil {
		return m.NumCallIn_180
	}
	return 0
}

func (m *Contact) GetPriorQual() bool {
	if m != nil {
		return m.PriorQual
	}
	return false
}

func (m *Contact) GetCreatedDt() int64 {
	if m != nil {
		return m.CreatedDt
	}
	return 0
}

func (m *Contact) GetLastContactDt() int64 {
	if m != nil {
		return m.LastContactDt
	}
	return 0
}

type ScheduledTask struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ScheduledTime        int64    `protobuf:"varint,2,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScheduledTask) Reset()         { *m = ScheduledTask{} }
func (m *ScheduledTask) String() string { return proto.CompactTextString(m) }
func (*ScheduledTask) ProtoMessage()    {}
func (*ScheduledTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{7}
}

func (m *ScheduledTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduledTask.Unmarshal(m, b)
}
func (m *ScheduledTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduledTask.Marshal(b, m, deterministic)
}
func (m *ScheduledTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduledTask.Merge(m, src)
}
func (m *ScheduledTask) XXX_Size() int {
	return xxx_messageInfo_ScheduledTask.Size(m)
}
func (m *ScheduledTask) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduledTask.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduledTask proto.InternalMessageInfo

func (m *ScheduledTask) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ScheduledTask) GetScheduledTime() int64 {
	if m != nil {
		return m.ScheduledTime
	}
	return 0
}

type ScoreCallResult struct {
	CallId               int64    `protobuf:"varint,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Score                int64    `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScoreCallResult) Reset()         { *m = ScoreCallResult{} }
func (m *ScoreCallResult) String() string { return proto.CompactTextString(m) }
func (*ScoreCallResult) ProtoMessage()    {}
func (*ScoreCallResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{8}
}

func (m *ScoreCallResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScoreCallResult.Unmarshal(m, b)
}
func (m *ScoreCallResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScoreCallResult.Marshal(b, m, deterministic)
}
func (m *ScoreCallResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScoreCallResult.Merge(m, src)
}
func (m *ScoreCallResult) XXX_Size() int {
	return xxx_messageInfo_ScoreCallResult.Size(m)
}
func (m *ScoreCallResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ScoreCallResult.DiscardUnknown(m)
}

var xxx_messageInfo_ScoreCallResult proto.InternalMessageInfo

func (m *ScoreCallResult) GetCallId() int64 {
	if m != nil {
		return m.CallId
	}
	return 0
}

func (m *ScoreCallResult) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

type SetScoringRuleEnabledRequest struct {
	RuleId               int64    `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	IsEnabled            bool     `protobuf:"varint,2,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetScoringRuleEnabledRequest) Reset()         { *m = SetScoringRuleEnabledRequest{} }
func (m *SetScoringRuleEnabledRequest) String() string { return proto.CompactTextString(m) }
func (*SetScoringRuleEnabledRequest) ProtoMessage()    {}
func (*SetScoringRuleEnabledRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{9}
}

func (m *SetScoringRuleEnabledRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetScoringRuleEnabledRequest.Unmarshal(m, b)
}
func (m *SetScoringRuleEnabledRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetScoringRuleEnabledRequest.Marshal(b, m, deterministic)
}
func (m *SetScoringRuleEnabledRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetScoringRuleEnabledRequest.Merge(m, src)
}
func (m *SetScoringRuleEnabledRequest) XXX_Size() int {
	return xxx_messageInfo_SetScoringRuleEnabledRequest.Size(m)
}
func (m *SetScoringRuleEnabledRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetScoringRuleEnabledRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetScoringRuleEnabledRequest proto.InternalMessageInfo

func (m *SetScoringRuleEnabledRequest) GetRuleId() int64 {
	if m != nil {
		return m.RuleId
	}
	return 0
}

func (m *SetScoringRuleEnabledRequest) GetIsEnabled() bool {
	if m != nil {
		return m.IsEnabled
	}
	return false
}

type CreateOrUpdateScoringRuleRequest struct {
	RuleId               int64           `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RuleName             string          `protobuf:"bytes,2,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	Description          string          `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Attribute            string          `protobuf:"bytes,4,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Prerequisites        []*Prerequisite `protobuf:"bytes,5,rep,name=prerequisites,proto3" json:"prerequisites,omitempty"`
	Scoring              []*Scoring      `protobuf:"bytes,6,rep,name=scoring,proto3" json:"scoring,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateOrUpdateScoringRuleRequest) Reset()         { *m = CreateOrUpdateScoringRuleRequest{} }
func (m *CreateOrUpdateScoringRuleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrUpdateScoringRuleRequest) ProtoMessage()    {}
func (*CreateOrUpdateScoringRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{10}
}

func (m *CreateOrUpdateScoringRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrUpdateScoringRuleRequest.Unmarshal(m, b)
}
func (m *CreateOrUpdateScoringRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrUpdateScoringRuleRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrUpdateScoringRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrUpdateScoringRuleRequest.Merge(m, src)
}
func (m *CreateOrUpdateScoringRuleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrUpdateScoringRuleRequest.Size(m)
}
func (m *CreateOrUpdateScoringRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrUpdateScoringRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrUpdateScoringRuleRequest proto.InternalMessageInfo

func (m *CreateOrUpdateScoringRuleRequest) GetRuleId() int64 {
	if m != nil {
		return m.RuleId
	}
	return 0
}

func (m *CreateOrUpdateScoringRuleRequest) GetRuleName() string {
	if m != nil {
		return m.RuleName
	}
	return ""
}

func (m *CreateOrUpdateScoringRuleRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateOrUpdateScoringRuleRequest) GetAttribute() string {
	if m != nil {
		return m.Attribute
	}
	return ""
}

func (m *CreateOrUpdateScoringRuleRequest) GetPrerequisites() []*Prerequisite {
	if m != nil {
		return m.Prerequisites
	}
	return nil
}

func (m *CreateOrUpdateScoringRuleRequest) GetScoring() []*Scoring {
	if m != nil {
		return m.Scoring
	}
	return nil
}

type ScoringRuleResult struct {
	RuleId               int64           `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	IsEnabled            bool            `protobuf:"varint,2,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	IsProdConfig         bool            `protobuf:"varint,3,opt,name=is_prod_config,json=isProdConfig,proto3" json:"is_prod_config,omitempty"`
	RuleName             string          `protobuf:"bytes,4,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	Description          string          `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Attribute            string          `protobuf:"bytes,6,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Prerequisites        []*Prerequisite `protobuf:"bytes,7,rep,name=prerequisites,proto3" json:"prerequisites,omitempty"`
	Scoring              []*Scoring      `protobuf:"bytes,8,rep,name=scoring,proto3" json:"scoring,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ScoringRuleResult) Reset()         { *m = ScoringRuleResult{} }
func (m *ScoringRuleResult) String() string { return proto.CompactTextString(m) }
func (*ScoringRuleResult) ProtoMessage()    {}
func (*ScoringRuleResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{11}
}

func (m *ScoringRuleResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScoringRuleResult.Unmarshal(m, b)
}
func (m *ScoringRuleResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScoringRuleResult.Marshal(b, m, deterministic)
}
func (m *ScoringRuleResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScoringRuleResult.Merge(m, src)
}
func (m *ScoringRuleResult) XXX_Size() int {
	return xxx_messageInfo_ScoringRuleResult.Size(m)
}
func (m *ScoringRuleResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ScoringRuleResult.DiscardUnknown(m)
}

var xxx_messageInfo_ScoringRuleResult proto.InternalMessageInfo

func (m *ScoringRuleResult) GetRuleId() int64 {
	if m != nil {
		return m.RuleId
	}
	return 0
}

func (m *ScoringRuleResult) GetIsEnabled() bool {
	if m != nil {
		return m.IsEnabled
	}
	return false
}

func (m *ScoringRuleResult) GetIsProdConfig() bool {
	if m != nil {
		return m.IsProdConfig
	}
	return false
}

func (m *ScoringRuleResult) GetRuleName() string {
	if m != nil {
		return m.RuleName
	}
	return ""
}

func (m *ScoringRuleResult) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ScoringRuleResult) GetAttribute() string {
	if m != nil {
		return m.Attribute
	}
	return ""
}

func (m *ScoringRuleResult) GetPrerequisites() []*Prerequisite {
	if m != nil {
		return m.Prerequisites
	}
	return nil
}

func (m *ScoringRuleResult) GetScoring() []*Scoring {
	if m != nil {
		return m.Scoring
	}
	return nil
}

type Prerequisite struct {
	PrerequisiteId       int64    `protobuf:"varint,1,opt,name=prerequisite_id,json=prerequisiteId,proto3" json:"prerequisite_id,omitempty"`
	Attribute            string   `protobuf:"bytes,2,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Comparator           string   `protobuf:"bytes,3,opt,name=comparator,proto3" json:"comparator,omitempty"`
	CheckValue           string   `protobuf:"bytes,4,opt,name=check_value,json=checkValue,proto3" json:"check_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prerequisite) Reset()         { *m = Prerequisite{} }
func (m *Prerequisite) String() string { return proto.CompactTextString(m) }
func (*Prerequisite) ProtoMessage()    {}
func (*Prerequisite) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{12}
}

func (m *Prerequisite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prerequisite.Unmarshal(m, b)
}
func (m *Prerequisite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prerequisite.Marshal(b, m, deterministic)
}
func (m *Prerequisite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prerequisite.Merge(m, src)
}
func (m *Prerequisite) XXX_Size() int {
	return xxx_messageInfo_Prerequisite.Size(m)
}
func (m *Prerequisite) XXX_DiscardUnknown() {
	xxx_messageInfo_Prerequisite.DiscardUnknown(m)
}

var xxx_messageInfo_Prerequisite proto.InternalMessageInfo

func (m *Prerequisite) GetPrerequisiteId() int64 {
	if m != nil {
		return m.PrerequisiteId
	}
	return 0
}

func (m *Prerequisite) GetAttribute() string {
	if m != nil {
		return m.Attribute
	}
	return ""
}

func (m *Prerequisite) GetComparator() string {
	if m != nil {
		return m.Comparator
	}
	return ""
}

func (m *Prerequisite) GetCheckValue() string {
	if m != nil {
		return m.CheckValue
	}
	return ""
}

type Scoring struct {
	ScoringId            int64    `protobuf:"varint,1,opt,name=scoring_id,json=scoringId,proto3" json:"scoring_id,omitempty"`
	Comparator           string   `protobuf:"bytes,2,opt,name=comparator,proto3" json:"comparator,omitempty"`
	CheckValue           string   `protobuf:"bytes,3,opt,name=check_value,json=checkValue,proto3" json:"check_value,omitempty"`
	Score                int64    `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Scoring) Reset()         { *m = Scoring{} }
func (m *Scoring) String() string { return proto.CompactTextString(m) }
func (*Scoring) ProtoMessage()    {}
func (*Scoring) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{13}
}

func (m *Scoring) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scoring.Unmarshal(m, b)
}
func (m *Scoring) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scoring.Marshal(b, m, deterministic)
}
func (m *Scoring) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scoring.Merge(m, src)
}
func (m *Scoring) XXX_Size() int {
	return xxx_messageInfo_Scoring.Size(m)
}
func (m *Scoring) XXX_DiscardUnknown() {
	xxx_messageInfo_Scoring.DiscardUnknown(m)
}

var xxx_messageInfo_Scoring proto.InternalMessageInfo

func (m *Scoring) GetScoringId() int64 {
	if m != nil {
		return m.ScoringId
	}
	return 0
}

func (m *Scoring) GetComparator() string {
	if m != nil {
		return m.Comparator
	}
	return ""
}

func (m *Scoring) GetCheckValue() string {
	if m != nil {
		return m.CheckValue
	}
	return ""
}

func (m *Scoring) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

type CreateOrUpdateScoringConfigurationRequest struct {
	ConfigId             int64         `protobuf:"varint,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	ConfigName           string        `protobuf:"bytes,2,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	ConfigRules          []*ConfigRule `protobuf:"bytes,3,rep,name=config_rules,json=configRules,proto3" json:"config_rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateOrUpdateScoringConfigurationRequest) Reset() {
	*m = CreateOrUpdateScoringConfigurationRequest{}
}
func (m *CreateOrUpdateScoringConfigurationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrUpdateScoringConfigurationRequest) ProtoMessage()    {}
func (*CreateOrUpdateScoringConfigurationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{14}
}

func (m *CreateOrUpdateScoringConfigurationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrUpdateScoringConfigurationRequest.Unmarshal(m, b)
}
func (m *CreateOrUpdateScoringConfigurationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrUpdateScoringConfigurationRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrUpdateScoringConfigurationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrUpdateScoringConfigurationRequest.Merge(m, src)
}
func (m *CreateOrUpdateScoringConfigurationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrUpdateScoringConfigurationRequest.Size(m)
}
func (m *CreateOrUpdateScoringConfigurationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrUpdateScoringConfigurationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrUpdateScoringConfigurationRequest proto.InternalMessageInfo

func (m *CreateOrUpdateScoringConfigurationRequest) GetConfigId() int64 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

func (m *CreateOrUpdateScoringConfigurationRequest) GetConfigName() string {
	if m != nil {
		return m.ConfigName
	}
	return ""
}

func (m *CreateOrUpdateScoringConfigurationRequest) GetConfigRules() []*ConfigRule {
	if m != nil {
		return m.ConfigRules
	}
	return nil
}

type SetScoringConfigurationProdOrEnabledRequest struct {
	ConfigId             int64    `protobuf:"varint,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	IsProd               bool     `protobuf:"varint,2,opt,name=is_prod,json=isProd,proto3" json:"is_prod,omitempty"`
	IsEnabled            bool     `protobuf:"varint,3,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetScoringConfigurationProdOrEnabledRequest) Reset() {
	*m = SetScoringConfigurationProdOrEnabledRequest{}
}
func (m *SetScoringConfigurationProdOrEnabledRequest) String() string {
	return proto.CompactTextString(m)
}
func (*SetScoringConfigurationProdOrEnabledRequest) ProtoMessage() {}
func (*SetScoringConfigurationProdOrEnabledRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{15}
}

func (m *SetScoringConfigurationProdOrEnabledRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetScoringConfigurationProdOrEnabledRequest.Unmarshal(m, b)
}
func (m *SetScoringConfigurationProdOrEnabledRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetScoringConfigurationProdOrEnabledRequest.Marshal(b, m, deterministic)
}
func (m *SetScoringConfigurationProdOrEnabledRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetScoringConfigurationProdOrEnabledRequest.Merge(m, src)
}
func (m *SetScoringConfigurationProdOrEnabledRequest) XXX_Size() int {
	return xxx_messageInfo_SetScoringConfigurationProdOrEnabledRequest.Size(m)
}
func (m *SetScoringConfigurationProdOrEnabledRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetScoringConfigurationProdOrEnabledRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetScoringConfigurationProdOrEnabledRequest proto.InternalMessageInfo

func (m *SetScoringConfigurationProdOrEnabledRequest) GetConfigId() int64 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

func (m *SetScoringConfigurationProdOrEnabledRequest) GetIsProd() bool {
	if m != nil {
		return m.IsProd
	}
	return false
}

func (m *SetScoringConfigurationProdOrEnabledRequest) GetIsEnabled() bool {
	if m != nil {
		return m.IsEnabled
	}
	return false
}

type ScoringConfigurationResult struct {
	ConfigId             int64         `protobuf:"varint,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	ConfigName           string        `protobuf:"bytes,2,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	IsProd               bool          `protobuf:"varint,3,opt,name=is_prod,json=isProd,proto3" json:"is_prod,omitempty"`
	IsEnabled            bool          `protobuf:"varint,4,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	ConfigRules          []*ConfigRule `protobuf:"bytes,5,rep,name=config_rules,json=configRules,proto3" json:"config_rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ScoringConfigurationResult) Reset()         { *m = ScoringConfigurationResult{} }
func (m *ScoringConfigurationResult) String() string { return proto.CompactTextString(m) }
func (*ScoringConfigurationResult) ProtoMessage()    {}
func (*ScoringConfigurationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{16}
}

func (m *ScoringConfigurationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScoringConfigurationResult.Unmarshal(m, b)
}
func (m *ScoringConfigurationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScoringConfigurationResult.Marshal(b, m, deterministic)
}
func (m *ScoringConfigurationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScoringConfigurationResult.Merge(m, src)
}
func (m *ScoringConfigurationResult) XXX_Size() int {
	return xxx_messageInfo_ScoringConfigurationResult.Size(m)
}
func (m *ScoringConfigurationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ScoringConfigurationResult.DiscardUnknown(m)
}

var xxx_messageInfo_ScoringConfigurationResult proto.InternalMessageInfo

func (m *ScoringConfigurationResult) GetConfigId() int64 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

func (m *ScoringConfigurationResult) GetConfigName() string {
	if m != nil {
		return m.ConfigName
	}
	return ""
}

func (m *ScoringConfigurationResult) GetIsProd() bool {
	if m != nil {
		return m.IsProd
	}
	return false
}

func (m *ScoringConfigurationResult) GetIsEnabled() bool {
	if m != nil {
		return m.IsEnabled
	}
	return false
}

func (m *ScoringConfigurationResult) GetConfigRules() []*ConfigRule {
	if m != nil {
		return m.ConfigRules
	}
	return nil
}

type GetScoringConfigurationsResponse struct {
	ScoringConfigurations []*ScoringConfigurationResult `protobuf:"bytes,1,rep,name=scoring_configurations,json=scoringConfigurations,proto3" json:"scoring_configurations,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                      `json:"-"`
	XXX_unrecognized      []byte                        `json:"-"`
	XXX_sizecache         int32                         `json:"-"`
}

func (m *GetScoringConfigurationsResponse) Reset()         { *m = GetScoringConfigurationsResponse{} }
func (m *GetScoringConfigurationsResponse) String() string { return proto.CompactTextString(m) }
func (*GetScoringConfigurationsResponse) ProtoMessage()    {}
func (*GetScoringConfigurationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{17}
}

func (m *GetScoringConfigurationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetScoringConfigurationsResponse.Unmarshal(m, b)
}
func (m *GetScoringConfigurationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetScoringConfigurationsResponse.Marshal(b, m, deterministic)
}
func (m *GetScoringConfigurationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetScoringConfigurationsResponse.Merge(m, src)
}
func (m *GetScoringConfigurationsResponse) XXX_Size() int {
	return xxx_messageInfo_GetScoringConfigurationsResponse.Size(m)
}
func (m *GetScoringConfigurationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetScoringConfigurationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetScoringConfigurationsResponse proto.InternalMessageInfo

func (m *GetScoringConfigurationsResponse) GetScoringConfigurations() []*ScoringConfigurationResult {
	if m != nil {
		return m.ScoringConfigurations
	}
	return nil
}

type ConfigRule struct {
	ConfigRuleId         int64    `protobuf:"varint,1,opt,name=config_rule_id,json=configRuleId,proto3" json:"config_rule_id,omitempty"`
	ConfigId             int64    `protobuf:"varint,2,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	RuleId               int64    `protobuf:"varint,3,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigRule) Reset()         { *m = ConfigRule{} }
func (m *ConfigRule) String() string { return proto.CompactTextString(m) }
func (*ConfigRule) ProtoMessage()    {}
func (*ConfigRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{18}
}

func (m *ConfigRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRule.Unmarshal(m, b)
}
func (m *ConfigRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRule.Marshal(b, m, deterministic)
}
func (m *ConfigRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRule.Merge(m, src)
}
func (m *ConfigRule) XXX_Size() int {
	return xxx_messageInfo_ConfigRule.Size(m)
}
func (m *ConfigRule) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRule.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRule proto.InternalMessageInfo

func (m *ConfigRule) GetConfigRuleId() int64 {
	if m != nil {
		return m.ConfigRuleId
	}
	return 0
}

func (m *ConfigRule) GetConfigId() int64 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

func (m *ConfigRule) GetRuleId() int64 {
	if m != nil {
		return m.RuleId
	}
	return 0
}

type GetAttributesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAttributesRequest) Reset()         { *m = GetAttributesRequest{} }
func (m *GetAttributesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAttributesRequest) ProtoMessage()    {}
func (*GetAttributesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{19}
}

func (m *GetAttributesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAttributesRequest.Unmarshal(m, b)
}
func (m *GetAttributesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAttributesRequest.Marshal(b, m, deterministic)
}
func (m *GetAttributesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAttributesRequest.Merge(m, src)
}
func (m *GetAttributesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAttributesRequest.Size(m)
}
func (m *GetAttributesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAttributesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAttributesRequest proto.InternalMessageInfo

type GetAttributesResponse struct {
	Attributes           []*Attribute `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetAttributesResponse) Reset()         { *m = GetAttributesResponse{} }
func (m *GetAttributesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAttributesResponse) ProtoMessage()    {}
func (*GetAttributesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{20}
}

func (m *GetAttributesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAttributesResponse.Unmarshal(m, b)
}
func (m *GetAttributesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAttributesResponse.Marshal(b, m, deterministic)
}
func (m *GetAttributesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAttributesResponse.Merge(m, src)
}
func (m *GetAttributesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAttributesResponse.Size(m)
}
func (m *GetAttributesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAttributesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAttributesResponse proto.InternalMessageInfo

func (m *GetAttributesResponse) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type Attribute struct {
	AttributeId          int64    `protobuf:"varint,1,opt,name=attribute_id,json=attributeId,proto3" json:"attribute_id,omitempty"`
	AttributeName        string   `protobuf:"bytes,2,opt,name=attribute_name,json=attributeName,proto3" json:"attribute_name,omitempty"`
	IsInt                bool     `protobuf:"varint,3,opt,name=is_int,json=isInt,proto3" json:"is_int,omitempty"`
	IsStatic             bool     `protobuf:"varint,4,opt,name=is_static,json=isStatic,proto3" json:"is_static,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{21}
}

func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (m *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(m, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetAttributeId() int64 {
	if m != nil {
		return m.AttributeId
	}
	return 0
}

func (m *Attribute) GetAttributeName() string {
	if m != nil {
		return m.AttributeName
	}
	return ""
}

func (m *Attribute) GetIsInt() bool {
	if m != nil {
		return m.IsInt
	}
	return false
}

func (m *Attribute) GetIsStatic() bool {
	if m != nil {
		return m.IsStatic
	}
	return false
}

type GetScoringRulesRequest struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetScoringRulesRequest) Reset()         { *m = GetScoringRulesRequest{} }
func (m *GetScoringRulesRequest) String() string { return proto.CompactTextString(m) }
func (*GetScoringRulesRequest) ProtoMessage()    {}
func (*GetScoringRulesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{22}
}

func (m *GetScoringRulesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetScoringRulesRequest.Unmarshal(m, b)
}
func (m *GetScoringRulesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetScoringRulesRequest.Marshal(b, m, deterministic)
}
func (m *GetScoringRulesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetScoringRulesRequest.Merge(m, src)
}
func (m *GetScoringRulesRequest) XXX_Size() int {
	return xxx_messageInfo_GetScoringRulesRequest.Size(m)
}
func (m *GetScoringRulesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetScoringRulesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetScoringRulesRequest proto.InternalMessageInfo

func (m *GetScoringRulesRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetScoringRulesRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetScoringRulesResult struct {
	Rules                []*ScoringRuleResult `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetScoringRulesResult) Reset()         { *m = GetScoringRulesResult{} }
func (m *GetScoringRulesResult) String() string { return proto.CompactTextString(m) }
func (*GetScoringRulesResult) ProtoMessage()    {}
func (*GetScoringRulesResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3caa3d1690debb, []int{23}
}

func (m *GetScoringRulesResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetScoringRulesResult.Unmarshal(m, b)
}
func (m *GetScoringRulesResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetScoringRulesResult.Marshal(b, m, deterministic)
}
func (m *GetScoringRulesResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetScoringRulesResult.Merge(m, src)
}
func (m *GetScoringRulesResult) XXX_Size() int {
	return xxx_messageInfo_GetScoringRulesResult.Size(m)
}
func (m *GetScoringRulesResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetScoringRulesResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetScoringRulesResult proto.InternalMessageInfo

func (m *GetScoringRulesResult) GetRules() []*ScoringRuleResult {
	if m != nil {
		return m.Rules
	}
	return nil
}

func init() {
	proto.RegisterType((*GetScoringConfigurationsRequest)(nil), "callscoring.GetScoringConfigurationsRequest")
	proto.RegisterType((*Flag)(nil), "callscoring.Flag")
	proto.RegisterType((*GetRuleByIdRequest)(nil), "callscoring.GetRuleByIdRequest")
	proto.RegisterType((*GetConfigByIdRequest)(nil), "callscoring.GetConfigByIdRequest")
	proto.RegisterType((*ScoreCallRequest)(nil), "callscoring.ScoreCallRequest")
	proto.RegisterType((*Inquiry)(nil), "callscoring.Inquiry")
	proto.RegisterType((*Contact)(nil), "callscoring.Contact")
	proto.RegisterType((*ScheduledTask)(nil), "callscoring.ScheduledTask")
	proto.RegisterType((*ScoreCallResult)(nil), "callscoring.ScoreCallResult")
	proto.RegisterType((*SetScoringRuleEnabledRequest)(nil), "callscoring.SetScoringRuleEnabledRequest")
	proto.RegisterType((*CreateOrUpdateScoringRuleRequest)(nil), "callscoring.CreateOrUpdateScoringRuleRequest")
	proto.RegisterType((*ScoringRuleResult)(nil), "callscoring.ScoringRuleResult")
	proto.RegisterType((*Prerequisite)(nil), "callscoring.Prerequisite")
	proto.RegisterType((*Scoring)(nil), "callscoring.Scoring")
	proto.RegisterType((*CreateOrUpdateScoringConfigurationRequest)(nil), "callscoring.CreateOrUpdateScoringConfigurationRequest")
	proto.RegisterType((*SetScoringConfigurationProdOrEnabledRequest)(nil), "callscoring.SetScoringConfigurationProdOrEnabledRequest")
	proto.RegisterType((*ScoringConfigurationResult)(nil), "callscoring.ScoringConfigurationResult")
	proto.RegisterType((*GetScoringConfigurationsResponse)(nil), "callscoring.GetScoringConfigurationsResponse")
	proto.RegisterType((*ConfigRule)(nil), "callscoring.ConfigRule")
	proto.RegisterType((*GetAttributesRequest)(nil), "callscoring.GetAttributesRequest")
	proto.RegisterType((*GetAttributesResponse)(nil), "callscoring.GetAttributesResponse")
	proto.RegisterType((*Attribute)(nil), "callscoring.Attribute")
	proto.RegisterType((*GetScoringRulesRequest)(nil), "callscoring.GetScoringRulesRequest")
	proto.RegisterType((*GetScoringRulesResult)(nil), "callscoring.GetScoringRulesResult")
}

func init() { proto.RegisterFile("callscoring.proto", fileDescriptor_0c3caa3d1690debb) }

var fileDescriptor_0c3caa3d1690debb = []byte{
	// 1503 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0xdd, 0x6e, 0xdb, 0xc6,
	0x12, 0x36, 0x25, 0xeb, 0x87, 0x23, 0x4b, 0x3e, 0x59, 0xd8, 0xb2, 0xa2, 0xfc, 0x58, 0x61, 0x92,
	0x13, 0xe7, 0x9c, 0x26, 0x50, 0xe2, 0x22, 0x48, 0x7a, 0xd3, 0x26, 0x4e, 0x63, 0x28, 0x40, 0xea,
	0x94, 0x4e, 0x73, 0x51, 0xb4, 0x25, 0x68, 0x72, 0x6d, 0x2d, 0x42, 0x91, 0x34, 0x77, 0x19, 0xc0,
	0x57, 0x05, 0x7a, 0x53, 0x04, 0xed, 0x75, 0xdf, 0xa0, 0xcf, 0xd1, 0x37, 0xe8, 0x03, 0xb4, 0xaf,
	0xd0, 0x87, 0x28, 0x76, 0x97, 0x3f, 0x4b, 0x4a, 0xb2, 0x94, 0xe4, 0x4e, 0xfb, 0xed, 0xc7, 0xd9,
	0xd9, 0x6f, 0x67, 0x66, 0x67, 0x05, 0x17, 0x1c, 0xdb, 0xf3, 0xa8, 0x13, 0x44, 0xc4, 0x3f, 0xb9,
	0x1b, 0x46, 0x01, 0x0b, 0x50, 0x4b, 0x81, 0x8c, 0xbf, 0x35, 0xd8, 0xde, 0xc7, 0xec, 0x50, 0x0e,
	0xf7, 0x02, 0xff, 0x98, 0x9c, 0xc4, 0x91, 0xcd, 0x48, 0xe0, 0x53, 0x13, 0x9f, 0xc6, 0x98, 0x32,
	0x74, 0x05, 0x80, 0x06, 0x11, 0xb3, 0x8e, 0x09, 0xf6, 0xdc, 0x9e, 0x36, 0xd0, 0x76, 0x74, 0x53,
	0xe7, 0xc8, 0x33, 0x0e, 0xa0, 0x9b, 0xd0, 0x11, 0xd3, 0x2e, 0x89, 0xb0, 0xc3, 0x3f, 0xec, 0x55,
	0x04, 0xa5, 0xcd, 0xd1, 0xa7, 0x29, 0x88, 0x36, 0xa0, 0xe6, 0x91, 0x09, 0x61, 0xbd, 0xea, 0x40,
	0xdb, 0xa9, 0x9a, 0x72, 0x80, 0x86, 0x00, 0x84, 0x5a, 0xd8, 0xb7, 0x8f, 0x3c, 0xec, 0xf6, 0x56,
	0x07, 0xda, 0x4e, 0xeb, 0xfe, 0x85, 0xbb, 0xaa, 0xd3, 0xcf, 0x3c, 0xfb, 0xc4, 0xd4, 0x09, 0xfd,
	0x52, 0x72, 0xd0, 0xff, 0xa0, 0x41, 0xa8, 0x15, 0x46, 0x81, 0xdb, 0xab, 0xcd, 0xa3, 0xd7, 0x09,
	0x7d, 0x19, 0x05, 0xae, 0xd1, 0x85, 0x55, 0x3e, 0x46, 0x1d, 0xa8, 0xb8, 0x81, 0xf0, 0xbc, 0x69,
	0x56, 0xdc, 0xc0, 0xb8, 0x03, 0x68, 0x1f, 0x33, 0x33, 0xf6, 0xf0, 0x93, 0xb3, 0x91, 0x9b, 0xee,
	0x73, 0x0b, 0x1a, 0x51, 0xec, 0x61, 0x8b, 0xc8, 0x4d, 0x56, 0xcd, 0x3a, 0x1f, 0x8e, 0x5c, 0x63,
	0x17, 0x36, 0xf6, 0x31, 0x93, 0xe2, 0xa8, 0x1f, 0x5c, 0x02, 0xdd, 0x11, 0x60, 0xfe, 0x49, 0x53,
	0x02, 0x23, 0xd7, 0xf8, 0xab, 0x02, 0xff, 0xe1, 0xb2, 0xe2, 0x3d, 0xdb, 0xf3, 0x94, 0x25, 0xb8,
	0xb3, 0xca, 0x12, 0x7c, 0x38, 0x12, 0x22, 0x8a, 0x89, 0x29, 0x11, 0x39, 0x9a, 0x8b, 0xb8, 0x0d,
	0xad, 0xb1, 0x4d, 0x2d, 0xe2, 0x9f, 0xc6, 0x24, 0x3a, 0x13, 0x52, 0x36, 0x4d, 0x18, 0xdb, 0x74,
	0x24, 0x11, 0x74, 0x17, 0x1a, 0xe9, 0xa4, 0x14, 0x73, 0xa3, 0xa0, 0x4e, 0x42, 0x33, 0x53, 0x52,
	0x6a, 0xd0, 0x09, 0x7c, 0x66, 0x3b, 0x4c, 0x28, 0x2a, 0x0d, 0xee, 0x49, 0x84, 0x1b, 0x4c, 0x27,
	0xeb, 0x33, 0x0c, 0x26, 0x34, 0x33, 0x25, 0xa1, 0x6b, 0xb0, 0x46, 0xa8, 0x45, 0x9d, 0x31, 0x76,
	0x63, 0x7e, 0xa4, 0x0d, 0x61, 0xb1, 0x45, 0xe8, 0x61, 0x0a, 0xa1, 0xc7, 0xd0, 0xc9, 0xe6, 0x2d,
	0x66, 0xd3, 0x37, 0xbd, 0xa6, 0xb0, 0xdc, 0x2f, 0x58, 0xce, 0xf8, 0xaf, 0x6c, 0xfa, 0xc6, 0x6c,
	0x53, 0x75, 0xc8, 0xc3, 0xb6, 0x91, 0x6e, 0xf9, 0x0a, 0x80, 0x13, 0x61, 0x9b, 0x61, 0xd7, 0x72,
	0x59, 0x22, 0xab, 0x9e, 0x20, 0x4f, 0x19, 0x42, 0xb0, 0xca, 0xce, 0x42, 0x9c, 0xe8, 0x29, 0x7e,
	0xa3, 0x1e, 0x34, 0x42, 0x3b, 0x62, 0x3e, 0x8e, 0x84, 0x84, 0xba, 0x99, 0x0e, 0x51, 0x17, 0xea,
	0x34, 0x88, 0x23, 0x07, 0x0b, 0xf9, 0x74, 0x33, 0x19, 0xa1, 0x5b, 0xb0, 0x2e, 0x4c, 0x92, 0xc0,
	0xb7, 0x26, 0x98, 0x8d, 0x93, 0xe8, 0xd3, 0xcd, 0x4e, 0x0a, 0xbf, 0x10, 0x28, 0x3f, 0xc8, 0x30,
	0x0a, 0xde, 0x12, 0x17, 0x47, 0x96, 0x33, 0xb6, 0x89, 0x2f, 0x64, 0xd3, 0xcd, 0x76, 0x8a, 0xee,
	0x71, 0x50, 0x84, 0x8e, 0x1d, 0x61, 0x4b, 0xb8, 0xd6, 0x10, 0x8c, 0x26, 0x07, 0x5e, 0x9d, 0x85,
	0xd8, 0xf8, 0xa7, 0x02, 0x8d, 0x54, 0xff, 0x6d, 0x68, 0xe1, 0x89, 0x4d, 0x3c, 0xeb, 0xad, 0xed,
	0x25, 0x51, 0xd3, 0x34, 0x41, 0x40, 0xaf, 0x39, 0xc2, 0x09, 0xe1, 0x38, 0xf0, 0x71, 0x42, 0xa8,
	0x48, 0x82, 0x80, 0x24, 0xc1, 0x80, 0xb5, 0x08, 0x7b, 0x32, 0xa5, 0xc7, 0x24, 0x4c, 0x76, 0x5c,
	0xc0, 0xd0, 0x0d, 0xe8, 0xf8, 0xf1, 0xc4, 0x0a, 0x23, 0x12, 0x44, 0x16, 0x3f, 0x05, 0xb1, 0xfd,
	0xaa, 0xb9, 0xe6, 0xc7, 0x93, 0x97, 0x1c, 0xe4, 0x41, 0x8c, 0xae, 0x4b, 0x96, 0x8c, 0x60, 0xdf,
	0xda, 0x1d, 0x0a, 0x0d, 0xaa, 0x66, 0xcb, 0x8f, 0x27, 0x9c, 0x30, 0xf2, 0x77, 0x87, 0x65, 0xd2,
	0xa3, 0xa1, 0x10, 0x40, 0x25, 0x3d, 0x1a, 0xa2, 0x9b, 0xb0, 0xae, 0x92, 0xee, 0x3d, 0x1c, 0x0a,
	0x11, 0xe4, 0x82, 0x92, 0x75, 0xef, 0xe1, 0x90, 0x1f, 0xad, 0x74, 0xe9, 0x34, 0xb6, 0x3d, 0x11,
	0x25, 0x4d, 0x53, 0x17, 0xc8, 0xd7, 0xb1, 0xed, 0x95, 0x4e, 0x5e, 0x2f, 0x9f, 0xfc, 0x7f, 0x61,
	0xdd, 0xb3, 0x29, 0x4b, 0x83, 0x9b, 0x73, 0x40, 0x70, 0xda, 0x1c, 0x4e, 0x04, 0x7e, 0xca, 0x8c,
	0xe7, 0xd0, 0x2e, 0x04, 0x5b, 0x16, 0x32, 0x9a, 0x12, 0x32, 0x37, 0x0b, 0x41, 0x4b, 0x26, 0x32,
	0xa0, 0xaa, 0x6a, 0x60, 0x92, 0x09, 0x36, 0xbe, 0x80, 0x75, 0x25, 0xe9, 0x69, 0xec, 0x9d, 0x93,
	0xf3, 0x1b, 0x50, 0xe3, 0xc1, 0x9e, 0x5a, 0x92, 0x03, 0xe3, 0x35, 0x5c, 0x3e, 0xcc, 0x0a, 0x32,
	0x2f, 0x51, 0x49, 0xe1, 0x5b, 0x54, 0xa5, 0xb8, 0x1a, 0x4a, 0x29, 0x95, 0x71, 0x90, 0xd7, 0x4d,
	0xe3, 0x5d, 0x05, 0x06, 0x7b, 0x42, 0x9b, 0x83, 0xe8, 0x9b, 0xd0, 0xb5, 0x19, 0x56, 0xd6, 0x58,
	0x68, 0xfc, 0x12, 0xe8, 0x62, 0xc2, 0xb7, 0x27, 0x69, 0x2a, 0x35, 0x39, 0xf0, 0x95, 0x3d, 0xc1,
	0x68, 0x00, 0x2d, 0x17, 0x53, 0x27, 0x22, 0xa1, 0xa8, 0x5c, 0x32, 0xc0, 0x54, 0x08, 0x5d, 0x06,
	0xdd, 0x66, 0x2c, 0x22, 0x47, 0x31, 0x4b, 0x33, 0x2b, 0x07, 0xd0, 0xe7, 0xd0, 0x0e, 0x23, 0x1c,
	0xe1, 0xd3, 0x98, 0x50, 0xc2, 0x30, 0xed, 0xd5, 0x06, 0xd5, 0x9d, 0xd6, 0xfd, 0x8b, 0x85, 0x7a,
	0xf0, 0x52, 0x61, 0x98, 0x45, 0x3e, 0x2f, 0x52, 0x09, 0xad, 0x57, 0x17, 0x9f, 0x6e, 0x94, 0x4a,
	0x89, 0xdc, 0x68, 0x4a, 0x32, 0xfe, 0xa8, 0xc0, 0x85, 0xc2, 0xee, 0xd3, 0x83, 0xfa, 0x10, 0x65,
	0x79, 0xf2, 0x24, 0x37, 0x92, 0x25, 0xab, 0x7f, 0x52, 0x97, 0xd7, 0xe4, 0x2d, 0x24, 0xef, 0x8d,
	0xa2, 0x82, 0xab, 0xe7, 0x2b, 0x58, 0x5b, 0xa0, 0x60, 0x7d, 0xa1, 0x82, 0x8d, 0x0f, 0x57, 0xb0,
	0xb9, 0x8c, 0x82, 0xbf, 0x69, 0xb0, 0xa6, 0xda, 0xe3, 0x05, 0x52, 0xb5, 0x98, 0x8b, 0xd8, 0x51,
	0xe1, 0x91, 0x5b, 0xdc, 0x48, 0xa5, 0xbc, 0x91, 0xab, 0x00, 0x4e, 0x30, 0x09, 0xed, 0xc8, 0x66,
	0x41, 0x5a, 0x9c, 0x15, 0x84, 0x57, 0x3b, 0x67, 0x8c, 0x9d, 0x37, 0xbc, 0xda, 0xc5, 0xa9, 0x8e,
	0x20, 0xa0, 0xd7, 0x1c, 0x31, 0x7e, 0x84, 0x46, 0xe2, 0xac, 0xe8, 0x5b, 0xe4, 0xcf, 0xdc, 0x1b,
	0x3d, 0x41, 0x46, 0x6e, 0x69, 0xa9, 0xca, 0xa2, 0xa5, 0xaa, 0xe5, 0xa5, 0xf2, 0xfc, 0x5d, 0x55,
	0xf3, 0xf7, 0x77, 0x0d, 0x6e, 0xcf, 0xcc, 0xb3, 0x42, 0x73, 0xb5, 0x4c, 0x0b, 0x21, 0x3c, 0x90,
	0x93, 0x4a, 0xda, 0x81, 0x84, 0x44, 0xd8, 0x7c, 0x06, 0x6b, 0x09, 0x81, 0x47, 0x12, 0xed, 0x55,
	0xc5, 0xd1, 0x6d, 0x95, 0x6f, 0xe8, 0x63, 0x22, 0xc3, 0x3c, 0xb1, 0xc6, 0x7f, 0x53, 0xe3, 0x27,
	0x0d, 0xfe, 0x7f, 0x38, 0xbb, 0xf3, 0xe3, 0x51, 0x7b, 0x10, 0x95, 0xea, 0xce, 0xb9, 0x9e, 0x6e,
	0xe5, 0x4d, 0x99, 0x4c, 0x8f, 0xa4, 0x03, 0x2b, 0xa5, 0x4e, 0xb5, 0x5c, 0x94, 0xfe, 0xd4, 0xa0,
	0x3f, 0x5b, 0x1e, 0x91, 0x91, 0x1f, 0xa7, 0x8e, 0xe2, 0x54, 0xf5, 0x1c, 0xa7, 0x56, 0xcb, 0xf9,
	0x5c, 0x56, 0xb5, 0xf6, 0x7e, 0xaa, 0x0e, 0xe6, 0xf7, 0xd3, 0x34, 0x0c, 0x7c, 0x8a, 0xd1, 0x0f,
	0xd0, 0x4d, 0x03, 0xd3, 0x29, 0x30, 0x7a, 0x9a, 0x58, 0xea, 0xd6, 0xac, 0xdc, 0x9b, 0xa1, 0x8f,
	0xb9, 0x49, 0x67, 0xad, 0x63, 0x8c, 0x01, 0x72, 0xff, 0x78, 0x79, 0x52, 0xb6, 0x93, 0x2b, 0xb9,
	0x96, 0xfb, 0x2d, 0x0b, 0x7c, 0x2e, 0x75, 0x65, 0xfa, 0x78, 0xd3, 0x6f, 0xab, 0x85, 0xce, 0xb8,
	0x2b, 0x3a, 0xe3, 0xc7, 0x69, 0xfa, 0xa6, 0x4f, 0x06, 0xe3, 0x00, 0x36, 0x4b, 0x78, 0xb2, 0xf5,
	0x07, 0x00, 0x59, 0xb2, 0xa7, 0xdb, 0xed, 0x16, 0xb6, 0x9b, 0x7d, 0x64, 0x2a, 0x4c, 0xe3, 0x9d,
	0x06, 0x7a, 0x36, 0xc3, 0x9b, 0xcc, 0x6c, 0x2e, 0xdf, 0x50, 0x2b, 0xc3, 0x64, 0x43, 0x9d, 0x53,
	0x94, 0x00, 0x69, 0x67, 0xa8, 0x88, 0x91, 0x4d, 0xa8, 0x13, 0xde, 0x4f, 0xb3, 0x24, 0x44, 0x6a,
	0x84, 0x8e, 0x7c, 0x11, 0x78, 0xbc, 0x8b, 0x65, 0x36, 0x23, 0x4e, 0x12, 0x20, 0x4d, 0x42, 0x0f,
	0xc5, 0xd8, 0x78, 0x06, 0xdd, 0xfd, 0xc2, 0x0d, 0x9d, 0xbd, 0x94, 0xb2, 0x37, 0x8e, 0xa6, 0xbe,
	0x71, 0xba, 0x50, 0x0f, 0x8e, 0x8f, 0x29, 0x66, 0x89, 0xae, 0xc9, 0xc8, 0x78, 0x21, 0x44, 0x2a,
	0xda, 0x11, 0x61, 0xff, 0x29, 0xd4, 0x64, 0xe4, 0x49, 0x7d, 0xae, 0xce, 0x2c, 0xc5, 0xd9, 0xbd,
	0x65, 0x4a, 0xf2, 0xfd, 0x5f, 0x75, 0x68, 0xed, 0xe5, 0x44, 0xf4, 0x1c, 0xf4, 0xac, 0x15, 0x41,
	0x57, 0xa6, 0x6c, 0xa8, 0xef, 0x92, 0xfe, 0xe5, 0x79, 0xd3, 0x7c, 0x01, 0x63, 0x05, 0x1d, 0x00,
	0x64, 0x20, 0xfd, 0x48, 0x63, 0x3b, 0xda, 0x50, 0x43, 0x1e, 0x5c, 0x9c, 0xdb, 0x8c, 0xa0, 0x3b,
	0xc5, 0x54, 0x5b, 0xd0, 0xb4, 0xf4, 0x17, 0xe8, 0x63, 0xac, 0xa0, 0x43, 0xe8, 0x14, 0x95, 0x46,
	0xdb, 0x85, 0x6f, 0xa6, 0x1f, 0x83, 0x4b, 0x18, 0xfd, 0x0e, 0xd6, 0x4b, 0xc7, 0x87, 0xae, 0x97,
	0xad, 0xce, 0x08, 0x92, 0xbe, 0x71, 0x3e, 0x29, 0xb1, 0xee, 0xc2, 0xe6, 0xcc, 0x36, 0x10, 0xdd,
	0x2e, 0x3a, 0x76, 0x4e, 0xab, 0xb8, 0xc4, 0x1e, 0x4e, 0x60, 0x6b, 0x4e, 0xb5, 0x42, 0xd7, 0xca,
	0x6e, 0x4e, 0xbd, 0x7f, 0xfb, 0xcb, 0xd6, 0x29, 0x63, 0x05, 0x9d, 0x41, 0x6f, 0x5e, 0x59, 0x44,
	0x9f, 0xcc, 0x11, 0x64, 0xe6, 0xbf, 0x11, 0xfd, 0x3b, 0x4b, 0xb2, 0x65, 0xc1, 0x31, 0x56, 0xd0,
	0xcf, 0x1a, 0x18, 0x8b, 0x2f, 0x64, 0xf4, 0x60, 0x71, 0xd0, 0xcd, 0xba, 0xc1, 0xdf, 0x47, 0x84,
	0x5f, 0x34, 0xb8, 0xb1, 0xcc, 0x95, 0x8b, 0x1e, 0xce, 0x39, 0xe3, 0x85, 0xb7, 0xf4, 0xfb, 0x78,
	0xf3, 0xbd, 0xf8, 0x13, 0x44, 0xbc, 0x11, 0xf3, 0x42, 0x3d, 0x7d, 0xec, 0x53, 0xc5, 0x7d, 0x3a,
	0x80, 0xa7, 0xeb, 0xbc, 0xb1, 0xf2, 0x64, 0xf5, 0xdb, 0x4a, 0x78, 0x74, 0x54, 0x17, 0xff, 0x39,
	0xed, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xce, 0xe6, 0x4e, 0x40, 0x88, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CallscoringClient is the client API for Callscoring service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CallscoringClient interface {
	ScoreCall(ctx context.Context, in *ScoreCallRequest, opts ...grpc.CallOption) (*ScoreCallResult, error)
	ScoreCalls(ctx context.Context, opts ...grpc.CallOption) (Callscoring_ScoreCallsClient, error)
	CreateOrUpdateScoringRule(ctx context.Context, in *CreateOrUpdateScoringRuleRequest, opts ...grpc.CallOption) (*ScoringRuleResult, error)
	GetScoringRule(ctx context.Context, in *GetRuleByIdRequest, opts ...grpc.CallOption) (*ScoringRuleResult, error)
	GetScoringRules(ctx context.Context, in *GetScoringRulesRequest, opts ...grpc.CallOption) (*GetScoringRulesResult, error)
	SetScoringRuleEnabled(ctx context.Context, in *SetScoringRuleEnabledRequest, opts ...grpc.CallOption) (*ScoringRuleResult, error)
	GetScoringConfiguration(ctx context.Context, in *GetConfigByIdRequest, opts ...grpc.CallOption) (*ScoringConfigurationResult, error)
	GetScoringConfigurations(ctx context.Context, in *GetScoringConfigurationsRequest, opts ...grpc.CallOption) (*GetScoringConfigurationsResponse, error)
	CreateOrUpdateScoringConfiguration(ctx context.Context, in *CreateOrUpdateScoringConfigurationRequest, opts ...grpc.CallOption) (*ScoringConfigurationResult, error)
	SetScoringConfigurationProdOrEnabled(ctx context.Context, in *SetScoringConfigurationProdOrEnabledRequest, opts ...grpc.CallOption) (*ScoringConfigurationResult, error)
	GetValidAttributes(ctx context.Context, in *GetAttributesRequest, opts ...grpc.CallOption) (*GetAttributesResponse, error)
}

type callscoringClient struct {
	cc *grpc.ClientConn
}

func NewCallscoringClient(cc *grpc.ClientConn) CallscoringClient {
	return &callscoringClient{cc}
}

func (c *callscoringClient) ScoreCall(ctx context.Context, in *ScoreCallRequest, opts ...grpc.CallOption) (*ScoreCallResult, error) {
	out := new(ScoreCallResult)
	err := c.cc.Invoke(ctx, "/callscoring.Callscoring/ScoreCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callscoringClient) ScoreCalls(ctx context.Context, opts ...grpc.CallOption) (Callscoring_ScoreCallsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Callscoring_serviceDesc.Streams[0], "/callscoring.Callscoring/ScoreCalls", opts...)
	if err != nil {
		return nil, err
	}
	x := &callscoringScoreCallsClient{stream}
	return x, nil
}

type Callscoring_ScoreCallsClient interface {
	Send(*ScoreCallRequest) error
	Recv() (*ScoreCallResult, error)
	grpc.ClientStream
}

type callscoringScoreCallsClient struct {
	grpc.ClientStream
}

func (x *callscoringScoreCallsClient) Send(m *ScoreCallRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *callscoringScoreCallsClient) Recv() (*ScoreCallResult, error) {
	m := new(ScoreCallResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *callscoringClient) CreateOrUpdateScoringRule(ctx context.Context, in *CreateOrUpdateScoringRuleRequest, opts ...grpc.CallOption) (*ScoringRuleResult, error) {
	out := new(ScoringRuleResult)
	err := c.cc.Invoke(ctx, "/callscoring.Callscoring/CreateOrUpdateScoringRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callscoringClient) GetScoringRule(ctx context.Context, in *GetRuleByIdRequest, opts ...grpc.CallOption) (*ScoringRuleResult, error) {
	out := new(ScoringRuleResult)
	err := c.cc.Invoke(ctx, "/callscoring.Callscoring/GetScoringRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callscoringClient) GetScoringRules(ctx context.Context, in *GetScoringRulesRequest, opts ...grpc.CallOption) (*GetScoringRulesResult, error) {
	out := new(GetScoringRulesResult)
	err := c.cc.Invoke(ctx, "/callscoring.Callscoring/GetScoringRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callscoringClient) SetScoringRuleEnabled(ctx context.Context, in *SetScoringRuleEnabledRequest, opts ...grpc.CallOption) (*ScoringRuleResult, error) {
	out := new(ScoringRuleResult)
	err := c.cc.Invoke(ctx, "/callscoring.Callscoring/SetScoringRuleEnabled", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callscoringClient) GetScoringConfiguration(ctx context.Context, in *GetConfigByIdRequest, opts ...grpc.CallOption) (*ScoringConfigurationResult, error) {
	out := new(ScoringConfigurationResult)
	err := c.cc.Invoke(ctx, "/callscoring.Callscoring/GetScoringConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callscoringClient) GetScoringConfigurations(ctx context.Context, in *GetScoringConfigurationsRequest, opts ...grpc.CallOption) (*GetScoringConfigurationsResponse, error) {
	out := new(GetScoringConfigurationsResponse)
	err := c.cc.Invoke(ctx, "/callscoring.Callscoring/GetScoringConfigurations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callscoringClient) CreateOrUpdateScoringConfiguration(ctx context.Context, in *CreateOrUpdateScoringConfigurationRequest, opts ...grpc.CallOption) (*ScoringConfigurationResult, error) {
	out := new(ScoringConfigurationResult)
	err := c.cc.Invoke(ctx, "/callscoring.Callscoring/CreateOrUpdateScoringConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callscoringClient) SetScoringConfigurationProdOrEnabled(ctx context.Context, in *SetScoringConfigurationProdOrEnabledRequest, opts ...grpc.CallOption) (*ScoringConfigurationResult, error) {
	out := new(ScoringConfigurationResult)
	err := c.cc.Invoke(ctx, "/callscoring.Callscoring/SetScoringConfigurationProdOrEnabled", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callscoringClient) GetValidAttributes(ctx context.Context, in *GetAttributesRequest, opts ...grpc.CallOption) (*GetAttributesResponse, error) {
	out := new(GetAttributesResponse)
	err := c.cc.Invoke(ctx, "/callscoring.Callscoring/GetValidAttributes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallscoringServer is the server API for Callscoring service.
type CallscoringServer interface {
	ScoreCall(context.Context, *ScoreCallRequest) (*ScoreCallResult, error)
	ScoreCalls(Callscoring_ScoreCallsServer) error
	CreateOrUpdateScoringRule(context.Context, *CreateOrUpdateScoringRuleRequest) (*ScoringRuleResult, error)
	GetScoringRule(context.Context, *GetRuleByIdRequest) (*ScoringRuleResult, error)
	GetScoringRules(context.Context, *GetScoringRulesRequest) (*GetScoringRulesResult, error)
	SetScoringRuleEnabled(context.Context, *SetScoringRuleEnabledRequest) (*ScoringRuleResult, error)
	GetScoringConfiguration(context.Context, *GetConfigByIdRequest) (*ScoringConfigurationResult, error)
	GetScoringConfigurations(context.Context, *GetScoringConfigurationsRequest) (*GetScoringConfigurationsResponse, error)
	CreateOrUpdateScoringConfiguration(context.Context, *CreateOrUpdateScoringConfigurationRequest) (*ScoringConfigurationResult, error)
	SetScoringConfigurationProdOrEnabled(context.Context, *SetScoringConfigurationProdOrEnabledRequest) (*ScoringConfigurationResult, error)
	GetValidAttributes(context.Context, *GetAttributesRequest) (*GetAttributesResponse, error)
}

// UnimplementedCallscoringServer can be embedded to have forward compatible implementations.
type UnimplementedCallscoringServer struct {
}

func (*UnimplementedCallscoringServer) ScoreCall(ctx context.Context, req *ScoreCallRequest) (*ScoreCallResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScoreCall not implemented")
}
func (*UnimplementedCallscoringServer) ScoreCalls(srv Callscoring_ScoreCallsServer) error {
	return status.Errorf(codes.Unimplemented, "method ScoreCalls not implemented")
}
func (*UnimplementedCallscoringServer) CreateOrUpdateScoringRule(ctx context.Context, req *CreateOrUpdateScoringRuleRequest) (*ScoringRuleResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrUpdateScoringRule not implemented")
}
func (*UnimplementedCallscoringServer) GetScoringRule(ctx context.Context, req *GetRuleByIdRequest) (*ScoringRuleResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScoringRule not implemented")
}
func (*UnimplementedCallscoringServer) GetScoringRules(ctx context.Context, req *GetScoringRulesRequest) (*GetScoringRulesResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScoringRules not implemented")
}
func (*UnimplementedCallscoringServer) SetScoringRuleEnabled(ctx context.Context, req *SetScoringRuleEnabledRequest) (*ScoringRuleResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetScoringRuleEnabled not implemented")
}
func (*UnimplementedCallscoringServer) GetScoringConfiguration(ctx context.Context, req *GetConfigByIdRequest) (*ScoringConfigurationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScoringConfiguration not implemented")
}
func (*UnimplementedCallscoringServer) GetScoringConfigurations(ctx context.Context, req *GetScoringConfigurationsRequest) (*GetScoringConfigurationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScoringConfigurations not implemented")
}
func (*UnimplementedCallscoringServer) CreateOrUpdateScoringConfiguration(ctx context.Context, req *CreateOrUpdateScoringConfigurationRequest) (*ScoringConfigurationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrUpdateScoringConfiguration not implemented")
}
func (*UnimplementedCallscoringServer) SetScoringConfigurationProdOrEnabled(ctx context.Context, req *SetScoringConfigurationProdOrEnabledRequest) (*ScoringConfigurationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetScoringConfigurationProdOrEnabled not implemented")
}
func (*UnimplementedCallscoringServer) GetValidAttributes(ctx context.Context, req *GetAttributesRequest) (*GetAttributesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidAttributes not implemented")
}

func RegisterCallscoringServer(s *grpc.Server, srv CallscoringServer) {
	s.RegisterService(&_Callscoring_serviceDesc, srv)
}

func _Callscoring_ScoreCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallscoringServer).ScoreCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/callscoring.Callscoring/ScoreCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallscoringServer).ScoreCall(ctx, req.(*ScoreCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Callscoring_ScoreCalls_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CallscoringServer).ScoreCalls(&callscoringScoreCallsServer{stream})
}

type Callscoring_ScoreCallsServer interface {
	Send(*ScoreCallResult) error
	Recv() (*ScoreCallRequest, error)
	grpc.ServerStream
}

type callscoringScoreCallsServer struct {
	grpc.ServerStream
}

func (x *callscoringScoreCallsServer) Send(m *ScoreCallResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *callscoringScoreCallsServer) Recv() (*ScoreCallRequest, error) {
	m := new(ScoreCallRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Callscoring_CreateOrUpdateScoringRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateScoringRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallscoringServer).CreateOrUpdateScoringRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/callscoring.Callscoring/CreateOrUpdateScoringRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallscoringServer).CreateOrUpdateScoringRule(ctx, req.(*CreateOrUpdateScoringRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Callscoring_GetScoringRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallscoringServer).GetScoringRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/callscoring.Callscoring/GetScoringRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallscoringServer).GetScoringRule(ctx, req.(*GetRuleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Callscoring_GetScoringRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScoringRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallscoringServer).GetScoringRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/callscoring.Callscoring/GetScoringRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallscoringServer).GetScoringRules(ctx, req.(*GetScoringRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Callscoring_SetScoringRuleEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetScoringRuleEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallscoringServer).SetScoringRuleEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/callscoring.Callscoring/SetScoringRuleEnabled",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallscoringServer).SetScoringRuleEnabled(ctx, req.(*SetScoringRuleEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Callscoring_GetScoringConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallscoringServer).GetScoringConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/callscoring.Callscoring/GetScoringConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallscoringServer).GetScoringConfiguration(ctx, req.(*GetConfigByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Callscoring_GetScoringConfigurations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScoringConfigurationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallscoringServer).GetScoringConfigurations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/callscoring.Callscoring/GetScoringConfigurations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallscoringServer).GetScoringConfigurations(ctx, req.(*GetScoringConfigurationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Callscoring_CreateOrUpdateScoringConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateScoringConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallscoringServer).CreateOrUpdateScoringConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/callscoring.Callscoring/CreateOrUpdateScoringConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallscoringServer).CreateOrUpdateScoringConfiguration(ctx, req.(*CreateOrUpdateScoringConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Callscoring_SetScoringConfigurationProdOrEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetScoringConfigurationProdOrEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallscoringServer).SetScoringConfigurationProdOrEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/callscoring.Callscoring/SetScoringConfigurationProdOrEnabled",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallscoringServer).SetScoringConfigurationProdOrEnabled(ctx, req.(*SetScoringConfigurationProdOrEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Callscoring_GetValidAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallscoringServer).GetValidAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/callscoring.Callscoring/GetValidAttributes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallscoringServer).GetValidAttributes(ctx, req.(*GetAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Callscoring_serviceDesc = grpc.ServiceDesc{
	ServiceName: "callscoring.Callscoring",
	HandlerType: (*CallscoringServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScoreCall",
			Handler:    _Callscoring_ScoreCall_Handler,
		},
		{
			MethodName: "CreateOrUpdateScoringRule",
			Handler:    _Callscoring_CreateOrUpdateScoringRule_Handler,
		},
		{
			MethodName: "GetScoringRule",
			Handler:    _Callscoring_GetScoringRule_Handler,
		},
		{
			MethodName: "GetScoringRules",
			Handler:    _Callscoring_GetScoringRules_Handler,
		},
		{
			MethodName: "SetScoringRuleEnabled",
			Handler:    _Callscoring_SetScoringRuleEnabled_Handler,
		},
		{
			MethodName: "GetScoringConfiguration",
			Handler:    _Callscoring_GetScoringConfiguration_Handler,
		},
		{
			MethodName: "GetScoringConfigurations",
			Handler:    _Callscoring_GetScoringConfigurations_Handler,
		},
		{
			MethodName: "CreateOrUpdateScoringConfiguration",
			Handler:    _Callscoring_CreateOrUpdateScoringConfiguration_Handler,
		},
		{
			MethodName: "SetScoringConfigurationProdOrEnabled",
			Handler:    _Callscoring_SetScoringConfigurationProdOrEnabled_Handler,
		},
		{
			MethodName: "GetValidAttributes",
			Handler:    _Callscoring_GetValidAttributes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ScoreCalls",
			Handler:       _Callscoring_ScoreCalls_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "callscoring.proto",
}
